baseURL = 'https://blog.aksine-am.com/'
languageCode = 'en-us'

theme = 'ananke'

SectionPagesMenu = "main"

[languages]
[languages.en]
title = "Aksine's thoughts"
weight = 1
contentDir = "content"

[menu]

[[menu.main]]
    name = 'About'
    pageRef = '/about'
    weight = 20
[params]

  date_format = "January 2, 2006"
  showLastmod = true
  enableGitInfo = true
[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/Aksine"

[[params.ananke_socials]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/arnold-miranda-74bb3813b/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true